
namespace Centre_D_affaire.GestionSalleDeSport
{
    partial class FormGestionnaire
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormGestionnaire));
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.BTNQuitter = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BTNutilisateur = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BTNAchat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BTNPrésence = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnPaiment = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BTNPackage = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BTNVendeur = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BTNEntraineur = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BTNMembre = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BTNstatistique = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BTNfermer = new Bunifu.Framework.UI.BunifuTileButton();
            this.BTNredire = new Bunifu.Framework.UI.BunifuTileButton();
            this.Panel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.PAnelDesktop = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.Panel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 5;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.pictureBox1);
            this.bunifuPanel1.Controls.Add(this.BTNQuitter);
            this.bunifuPanel1.Controls.Add(this.BTNutilisateur);
            this.bunifuPanel1.Controls.Add(this.BTNAchat);
            this.bunifuPanel1.Controls.Add(this.BTNPrésence);
            this.bunifuPanel1.Controls.Add(this.btnPaiment);
            this.bunifuPanel1.Controls.Add(this.BTNPackage);
            this.bunifuPanel1.Controls.Add(this.BTNVendeur);
            this.bunifuPanel1.Controls.Add(this.BTNEntraineur);
            this.bunifuPanel1.Controls.Add(this.BTNMembre);
            this.bunifuPanel1.Controls.Add(this.BTNstatistique);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 46);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(267, 755);
            this.bunifuPanel1.TabIndex = 156;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(4, 0);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(259, 117);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 158;
            this.pictureBox1.TabStop = false;
            // 
            // BTNQuitter
            // 
            this.BTNQuitter.AllowAnimations = true;
            this.BTNQuitter.AllowMouseEffects = true;
            this.BTNQuitter.AllowToggling = false;
            this.BTNQuitter.AnimationSpeed = 200;
            this.BTNQuitter.AutoGenerateColors = false;
            this.BTNQuitter.AutoRoundBorders = false;
            this.BTNQuitter.AutoSizeLeftIcon = true;
            this.BTNQuitter.AutoSizeRightIcon = true;
            this.BTNQuitter.BackColor = System.Drawing.Color.Transparent;
            this.BTNQuitter.BackColor1 = System.Drawing.SystemColors.ButtonHighlight;
            this.BTNQuitter.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BTNQuitter.BackgroundImage")));
            this.BTNQuitter.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.BTNQuitter.ButtonText = "                  Se déconnecter";
            this.BTNQuitter.ButtonTextMarginLeft = 0;
            this.BTNQuitter.ColorContrastOnClick = 45;
            this.BTNQuitter.ColorContrastOnHover = 45;
            this.BTNQuitter.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.BTNQuitter.CustomizableEdges = borderEdges1;
            this.BTNQuitter.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BTNQuitter.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BTNQuitter.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BTNQuitter.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BTNQuitter.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BTNQuitter.Font = new System.Drawing.Font("Agency FB", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BTNQuitter.ForeColor = System.Drawing.Color.Black;
            this.BTNQuitter.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BTNQuitter.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BTNQuitter.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BTNQuitter.IconMarginLeft = 11;
            this.BTNQuitter.IconPadding = 10;
            this.BTNQuitter.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BTNQuitter.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BTNQuitter.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BTNQuitter.IconSize = 25;
            this.BTNQuitter.IdleBorderColor = System.Drawing.Color.Transparent;
            this.BTNQuitter.IdleBorderRadius = 1;
            this.BTNQuitter.IdleBorderThickness = 1;
            this.BTNQuitter.IdleFillColor = System.Drawing.SystemColors.ButtonHighlight;
            this.BTNQuitter.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("BTNQuitter.IdleIconLeftImage")));
            this.BTNQuitter.IdleIconRightImage = null;
            this.BTNQuitter.IndicateFocus = false;
            this.BTNQuitter.Location = new System.Drawing.Point(1, 705);
            this.BTNQuitter.Name = "BTNQuitter";
            this.BTNQuitter.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BTNQuitter.OnDisabledState.BorderRadius = 1;
            this.BTNQuitter.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNQuitter.OnDisabledState.BorderThickness = 1;
            this.BTNQuitter.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BTNQuitter.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BTNQuitter.OnDisabledState.IconLeftImage = null;
            this.BTNQuitter.OnDisabledState.IconRightImage = null;
            this.BTNQuitter.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BTNQuitter.onHoverState.BorderRadius = 1;
            this.BTNQuitter.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNQuitter.onHoverState.BorderThickness = 1;
            this.BTNQuitter.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BTNQuitter.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BTNQuitter.onHoverState.IconLeftImage = null;
            this.BTNQuitter.onHoverState.IconRightImage = null;
            this.BTNQuitter.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BTNQuitter.OnIdleState.BorderRadius = 1;
            this.BTNQuitter.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.BTNQuitter.OnIdleState.BorderThickness = 1;
            this.BTNQuitter.OnIdleState.FillColor = System.Drawing.SystemColors.ButtonHighlight;
            this.BTNQuitter.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.BTNQuitter.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("BTNQuitter.OnIdleState.IconLeftImage")));
            this.BTNQuitter.OnIdleState.IconRightImage = null;
            this.BTNQuitter.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BTNQuitter.OnPressedState.BorderRadius = 1;
            this.BTNQuitter.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNQuitter.OnPressedState.BorderThickness = 1;
            this.BTNQuitter.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BTNQuitter.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BTNQuitter.OnPressedState.IconLeftImage = null;
            this.BTNQuitter.OnPressedState.IconRightImage = null;
            this.BTNQuitter.Size = new System.Drawing.Size(266, 51);
            this.BTNQuitter.TabIndex = 160;
            this.BTNQuitter.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BTNQuitter.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BTNQuitter.TextMarginLeft = 0;
            this.BTNQuitter.TextPadding = new System.Windows.Forms.Padding(0);
            this.BTNQuitter.UseDefaultRadiusAndThickness = true;
            this.BTNQuitter.Click += new System.EventHandler(this.BTNQuitter_Click);
            // 
            // BTNutilisateur
            // 
            this.BTNutilisateur.AllowAnimations = true;
            this.BTNutilisateur.AllowMouseEffects = true;
            this.BTNutilisateur.AllowToggling = false;
            this.BTNutilisateur.AnimationSpeed = 200;
            this.BTNutilisateur.AutoGenerateColors = false;
            this.BTNutilisateur.AutoRoundBorders = false;
            this.BTNutilisateur.AutoSizeLeftIcon = true;
            this.BTNutilisateur.AutoSizeRightIcon = true;
            this.BTNutilisateur.BackColor = System.Drawing.Color.Transparent;
            this.BTNutilisateur.BackColor1 = System.Drawing.Color.White;
            this.BTNutilisateur.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BTNutilisateur.BackgroundImage")));
            this.BTNutilisateur.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.BTNutilisateur.ButtonText = "Utilisateurs";
            this.BTNutilisateur.ButtonTextMarginLeft = 0;
            this.BTNutilisateur.ColorContrastOnClick = 45;
            this.BTNutilisateur.ColorContrastOnHover = 45;
            this.BTNutilisateur.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.BTNutilisateur.CustomizableEdges = borderEdges2;
            this.BTNutilisateur.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BTNutilisateur.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BTNutilisateur.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BTNutilisateur.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BTNutilisateur.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BTNutilisateur.Font = new System.Drawing.Font("Agency FB", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BTNutilisateur.ForeColor = System.Drawing.Color.DimGray;
            this.BTNutilisateur.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BTNutilisateur.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BTNutilisateur.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BTNutilisateur.IconMarginLeft = 11;
            this.BTNutilisateur.IconPadding = 10;
            this.BTNutilisateur.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BTNutilisateur.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BTNutilisateur.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BTNutilisateur.IconSize = 25;
            this.BTNutilisateur.IdleBorderColor = System.Drawing.Color.Transparent;
            this.BTNutilisateur.IdleBorderRadius = 1;
            this.BTNutilisateur.IdleBorderThickness = 1;
            this.BTNutilisateur.IdleFillColor = System.Drawing.Color.White;
            this.BTNutilisateur.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("BTNutilisateur.IdleIconLeftImage")));
            this.BTNutilisateur.IdleIconRightImage = null;
            this.BTNutilisateur.IndicateFocus = false;
            this.BTNutilisateur.Location = new System.Drawing.Point(0, 643);
            this.BTNutilisateur.Name = "BTNutilisateur";
            this.BTNutilisateur.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BTNutilisateur.OnDisabledState.BorderRadius = 1;
            this.BTNutilisateur.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNutilisateur.OnDisabledState.BorderThickness = 1;
            this.BTNutilisateur.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BTNutilisateur.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BTNutilisateur.OnDisabledState.IconLeftImage = null;
            this.BTNutilisateur.OnDisabledState.IconRightImage = null;
            this.BTNutilisateur.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BTNutilisateur.onHoverState.BorderRadius = 1;
            this.BTNutilisateur.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNutilisateur.onHoverState.BorderThickness = 1;
            this.BTNutilisateur.onHoverState.FillColor = System.Drawing.Color.Fuchsia;
            this.BTNutilisateur.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BTNutilisateur.onHoverState.IconLeftImage = null;
            this.BTNutilisateur.onHoverState.IconRightImage = null;
            this.BTNutilisateur.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BTNutilisateur.OnIdleState.BorderRadius = 1;
            this.BTNutilisateur.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.BTNutilisateur.OnIdleState.BorderThickness = 1;
            this.BTNutilisateur.OnIdleState.FillColor = System.Drawing.Color.White;
            this.BTNutilisateur.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.BTNutilisateur.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("BTNutilisateur.OnIdleState.IconLeftImage")));
            this.BTNutilisateur.OnIdleState.IconRightImage = null;
            this.BTNutilisateur.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BTNutilisateur.OnPressedState.BorderRadius = 1;
            this.BTNutilisateur.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNutilisateur.OnPressedState.BorderThickness = 1;
            this.BTNutilisateur.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BTNutilisateur.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BTNutilisateur.OnPressedState.IconLeftImage = null;
            this.BTNutilisateur.OnPressedState.IconRightImage = null;
            this.BTNutilisateur.Size = new System.Drawing.Size(267, 53);
            this.BTNutilisateur.TabIndex = 15;
            this.BTNutilisateur.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BTNutilisateur.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BTNutilisateur.TextMarginLeft = 0;
            this.BTNutilisateur.TextPadding = new System.Windows.Forms.Padding(0);
            this.BTNutilisateur.UseDefaultRadiusAndThickness = true;
            this.BTNutilisateur.Click += new System.EventHandler(this.BTNutilisateur_Click);
            // 
            // BTNAchat
            // 
            this.BTNAchat.AllowAnimations = true;
            this.BTNAchat.AllowMouseEffects = true;
            this.BTNAchat.AllowToggling = false;
            this.BTNAchat.AnimationSpeed = 200;
            this.BTNAchat.AutoGenerateColors = false;
            this.BTNAchat.AutoRoundBorders = false;
            this.BTNAchat.AutoSizeLeftIcon = true;
            this.BTNAchat.AutoSizeRightIcon = true;
            this.BTNAchat.BackColor = System.Drawing.Color.Transparent;
            this.BTNAchat.BackColor1 = System.Drawing.Color.White;
            this.BTNAchat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BTNAchat.BackgroundImage")));
            this.BTNAchat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.BTNAchat.ButtonText = "Achats";
            this.BTNAchat.ButtonTextMarginLeft = 0;
            this.BTNAchat.ColorContrastOnClick = 45;
            this.BTNAchat.ColorContrastOnHover = 45;
            this.BTNAchat.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.BTNAchat.CustomizableEdges = borderEdges3;
            this.BTNAchat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BTNAchat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BTNAchat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BTNAchat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BTNAchat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BTNAchat.Font = new System.Drawing.Font("Agency FB", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BTNAchat.ForeColor = System.Drawing.Color.DimGray;
            this.BTNAchat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BTNAchat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BTNAchat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BTNAchat.IconMarginLeft = 11;
            this.BTNAchat.IconPadding = 10;
            this.BTNAchat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BTNAchat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BTNAchat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BTNAchat.IconSize = 25;
            this.BTNAchat.IdleBorderColor = System.Drawing.Color.Transparent;
            this.BTNAchat.IdleBorderRadius = 1;
            this.BTNAchat.IdleBorderThickness = 1;
            this.BTNAchat.IdleFillColor = System.Drawing.Color.White;
            this.BTNAchat.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("BTNAchat.IdleIconLeftImage")));
            this.BTNAchat.IdleIconRightImage = null;
            this.BTNAchat.IndicateFocus = false;
            this.BTNAchat.Location = new System.Drawing.Point(0, 539);
            this.BTNAchat.Name = "BTNAchat";
            this.BTNAchat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BTNAchat.OnDisabledState.BorderRadius = 1;
            this.BTNAchat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNAchat.OnDisabledState.BorderThickness = 1;
            this.BTNAchat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BTNAchat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BTNAchat.OnDisabledState.IconLeftImage = null;
            this.BTNAchat.OnDisabledState.IconRightImage = null;
            this.BTNAchat.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BTNAchat.onHoverState.BorderRadius = 1;
            this.BTNAchat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNAchat.onHoverState.BorderThickness = 1;
            this.BTNAchat.onHoverState.FillColor = System.Drawing.Color.Maroon;
            this.BTNAchat.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BTNAchat.onHoverState.IconLeftImage = null;
            this.BTNAchat.onHoverState.IconRightImage = null;
            this.BTNAchat.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BTNAchat.OnIdleState.BorderRadius = 1;
            this.BTNAchat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.BTNAchat.OnIdleState.BorderThickness = 1;
            this.BTNAchat.OnIdleState.FillColor = System.Drawing.Color.White;
            this.BTNAchat.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.BTNAchat.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("BTNAchat.OnIdleState.IconLeftImage")));
            this.BTNAchat.OnIdleState.IconRightImage = null;
            this.BTNAchat.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BTNAchat.OnPressedState.BorderRadius = 1;
            this.BTNAchat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNAchat.OnPressedState.BorderThickness = 1;
            this.BTNAchat.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BTNAchat.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BTNAchat.OnPressedState.IconLeftImage = null;
            this.BTNAchat.OnPressedState.IconRightImage = null;
            this.BTNAchat.Size = new System.Drawing.Size(267, 53);
            this.BTNAchat.TabIndex = 14;
            this.BTNAchat.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BTNAchat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BTNAchat.TextMarginLeft = 0;
            this.BTNAchat.TextPadding = new System.Windows.Forms.Padding(0);
            this.BTNAchat.UseDefaultRadiusAndThickness = true;
            this.BTNAchat.Click += new System.EventHandler(this.BTNAchat_Click);
            // 
            // BTNPrésence
            // 
            this.BTNPrésence.AllowAnimations = true;
            this.BTNPrésence.AllowMouseEffects = true;
            this.BTNPrésence.AllowToggling = false;
            this.BTNPrésence.AnimationSpeed = 200;
            this.BTNPrésence.AutoGenerateColors = false;
            this.BTNPrésence.AutoRoundBorders = false;
            this.BTNPrésence.AutoSizeLeftIcon = true;
            this.BTNPrésence.AutoSizeRightIcon = true;
            this.BTNPrésence.BackColor = System.Drawing.Color.Transparent;
            this.BTNPrésence.BackColor1 = System.Drawing.Color.White;
            this.BTNPrésence.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BTNPrésence.BackgroundImage")));
            this.BTNPrésence.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.BTNPrésence.ButtonText = "Présence";
            this.BTNPrésence.ButtonTextMarginLeft = 0;
            this.BTNPrésence.ColorContrastOnClick = 45;
            this.BTNPrésence.ColorContrastOnHover = 45;
            this.BTNPrésence.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.BTNPrésence.CustomizableEdges = borderEdges4;
            this.BTNPrésence.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BTNPrésence.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BTNPrésence.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BTNPrésence.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BTNPrésence.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BTNPrésence.Font = new System.Drawing.Font("Agency FB", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BTNPrésence.ForeColor = System.Drawing.Color.DimGray;
            this.BTNPrésence.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BTNPrésence.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BTNPrésence.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BTNPrésence.IconMarginLeft = 11;
            this.BTNPrésence.IconPadding = 10;
            this.BTNPrésence.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BTNPrésence.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BTNPrésence.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BTNPrésence.IconSize = 25;
            this.BTNPrésence.IdleBorderColor = System.Drawing.Color.Transparent;
            this.BTNPrésence.IdleBorderRadius = 1;
            this.BTNPrésence.IdleBorderThickness = 1;
            this.BTNPrésence.IdleFillColor = System.Drawing.Color.White;
            this.BTNPrésence.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("BTNPrésence.IdleIconLeftImage")));
            this.BTNPrésence.IdleIconRightImage = null;
            this.BTNPrésence.IndicateFocus = false;
            this.BTNPrésence.Location = new System.Drawing.Point(0, 475);
            this.BTNPrésence.Name = "BTNPrésence";
            this.BTNPrésence.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BTNPrésence.OnDisabledState.BorderRadius = 1;
            this.BTNPrésence.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNPrésence.OnDisabledState.BorderThickness = 1;
            this.BTNPrésence.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BTNPrésence.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BTNPrésence.OnDisabledState.IconLeftImage = null;
            this.BTNPrésence.OnDisabledState.IconRightImage = null;
            this.BTNPrésence.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BTNPrésence.onHoverState.BorderRadius = 1;
            this.BTNPrésence.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNPrésence.onHoverState.BorderThickness = 1;
            this.BTNPrésence.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.BTNPrésence.onHoverState.ForeColor = System.Drawing.Color.SeaShell;
            this.BTNPrésence.onHoverState.IconLeftImage = null;
            this.BTNPrésence.onHoverState.IconRightImage = null;
            this.BTNPrésence.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BTNPrésence.OnIdleState.BorderRadius = 1;
            this.BTNPrésence.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.BTNPrésence.OnIdleState.BorderThickness = 1;
            this.BTNPrésence.OnIdleState.FillColor = System.Drawing.Color.White;
            this.BTNPrésence.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.BTNPrésence.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("BTNPrésence.OnIdleState.IconLeftImage")));
            this.BTNPrésence.OnIdleState.IconRightImage = null;
            this.BTNPrésence.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BTNPrésence.OnPressedState.BorderRadius = 1;
            this.BTNPrésence.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNPrésence.OnPressedState.BorderThickness = 1;
            this.BTNPrésence.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BTNPrésence.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BTNPrésence.OnPressedState.IconLeftImage = null;
            this.BTNPrésence.OnPressedState.IconRightImage = null;
            this.BTNPrésence.Size = new System.Drawing.Size(267, 53);
            this.BTNPrésence.TabIndex = 13;
            this.BTNPrésence.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BTNPrésence.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BTNPrésence.TextMarginLeft = 0;
            this.BTNPrésence.TextPadding = new System.Windows.Forms.Padding(0);
            this.BTNPrésence.UseDefaultRadiusAndThickness = true;
            this.BTNPrésence.Click += new System.EventHandler(this.BTNPrésence_Click);
            // 
            // btnPaiment
            // 
            this.btnPaiment.AllowAnimations = true;
            this.btnPaiment.AllowMouseEffects = true;
            this.btnPaiment.AllowToggling = false;
            this.btnPaiment.AnimationSpeed = 200;
            this.btnPaiment.AutoGenerateColors = false;
            this.btnPaiment.AutoRoundBorders = false;
            this.btnPaiment.AutoSizeLeftIcon = true;
            this.btnPaiment.AutoSizeRightIcon = true;
            this.btnPaiment.BackColor = System.Drawing.Color.Transparent;
            this.btnPaiment.BackColor1 = System.Drawing.Color.White;
            this.btnPaiment.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPaiment.BackgroundImage")));
            this.btnPaiment.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.btnPaiment.ButtonText = "Paiement";
            this.btnPaiment.ButtonTextMarginLeft = 0;
            this.btnPaiment.ColorContrastOnClick = 45;
            this.btnPaiment.ColorContrastOnHover = 45;
            this.btnPaiment.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnPaiment.CustomizableEdges = borderEdges5;
            this.btnPaiment.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnPaiment.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPaiment.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPaiment.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPaiment.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnPaiment.Font = new System.Drawing.Font("Agency FB", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPaiment.ForeColor = System.Drawing.Color.DimGray;
            this.btnPaiment.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPaiment.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnPaiment.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnPaiment.IconMarginLeft = 11;
            this.btnPaiment.IconPadding = 10;
            this.btnPaiment.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPaiment.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnPaiment.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnPaiment.IconSize = 25;
            this.btnPaiment.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnPaiment.IdleBorderRadius = 1;
            this.btnPaiment.IdleBorderThickness = 1;
            this.btnPaiment.IdleFillColor = System.Drawing.Color.White;
            this.btnPaiment.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnPaiment.IdleIconLeftImage")));
            this.btnPaiment.IdleIconRightImage = null;
            this.btnPaiment.IndicateFocus = false;
            this.btnPaiment.Location = new System.Drawing.Point(0, 416);
            this.btnPaiment.Name = "btnPaiment";
            this.btnPaiment.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPaiment.OnDisabledState.BorderRadius = 1;
            this.btnPaiment.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPaiment.OnDisabledState.BorderThickness = 1;
            this.btnPaiment.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPaiment.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPaiment.OnDisabledState.IconLeftImage = null;
            this.btnPaiment.OnDisabledState.IconRightImage = null;
            this.btnPaiment.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnPaiment.onHoverState.BorderRadius = 1;
            this.btnPaiment.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPaiment.onHoverState.BorderThickness = 1;
            this.btnPaiment.onHoverState.FillColor = System.Drawing.Color.LawnGreen;
            this.btnPaiment.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnPaiment.onHoverState.IconLeftImage = null;
            this.btnPaiment.onHoverState.IconRightImage = null;
            this.btnPaiment.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnPaiment.OnIdleState.BorderRadius = 1;
            this.btnPaiment.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.btnPaiment.OnIdleState.BorderThickness = 1;
            this.btnPaiment.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnPaiment.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.btnPaiment.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnPaiment.OnIdleState.IconLeftImage")));
            this.btnPaiment.OnIdleState.IconRightImage = null;
            this.btnPaiment.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnPaiment.OnPressedState.BorderRadius = 1;
            this.btnPaiment.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPaiment.OnPressedState.BorderThickness = 1;
            this.btnPaiment.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnPaiment.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnPaiment.OnPressedState.IconLeftImage = null;
            this.btnPaiment.OnPressedState.IconRightImage = null;
            this.btnPaiment.Size = new System.Drawing.Size(267, 53);
            this.btnPaiment.TabIndex = 12;
            this.btnPaiment.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnPaiment.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnPaiment.TextMarginLeft = 0;
            this.btnPaiment.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnPaiment.UseDefaultRadiusAndThickness = true;
            this.btnPaiment.Click += new System.EventHandler(this.btnPaiment_Click);
            // 
            // BTNPackage
            // 
            this.BTNPackage.AllowAnimations = true;
            this.BTNPackage.AllowMouseEffects = true;
            this.BTNPackage.AllowToggling = false;
            this.BTNPackage.AnimationSpeed = 200;
            this.BTNPackage.AutoGenerateColors = false;
            this.BTNPackage.AutoRoundBorders = false;
            this.BTNPackage.AutoSizeLeftIcon = true;
            this.BTNPackage.AutoSizeRightIcon = true;
            this.BTNPackage.BackColor = System.Drawing.Color.Transparent;
            this.BTNPackage.BackColor1 = System.Drawing.Color.White;
            this.BTNPackage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BTNPackage.BackgroundImage")));
            this.BTNPackage.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.BTNPackage.ButtonText = "Package";
            this.BTNPackage.ButtonTextMarginLeft = 0;
            this.BTNPackage.ColorContrastOnClick = 45;
            this.BTNPackage.ColorContrastOnHover = 45;
            this.BTNPackage.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.BTNPackage.CustomizableEdges = borderEdges6;
            this.BTNPackage.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BTNPackage.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BTNPackage.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BTNPackage.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BTNPackage.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BTNPackage.Font = new System.Drawing.Font("Agency FB", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BTNPackage.ForeColor = System.Drawing.Color.DimGray;
            this.BTNPackage.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BTNPackage.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BTNPackage.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BTNPackage.IconMarginLeft = 11;
            this.BTNPackage.IconPadding = 10;
            this.BTNPackage.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BTNPackage.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BTNPackage.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BTNPackage.IconSize = 25;
            this.BTNPackage.IdleBorderColor = System.Drawing.Color.Transparent;
            this.BTNPackage.IdleBorderRadius = 1;
            this.BTNPackage.IdleBorderThickness = 1;
            this.BTNPackage.IdleFillColor = System.Drawing.Color.White;
            this.BTNPackage.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("BTNPackage.IdleIconLeftImage")));
            this.BTNPackage.IdleIconRightImage = null;
            this.BTNPackage.IndicateFocus = false;
            this.BTNPackage.Location = new System.Drawing.Point(0, 286);
            this.BTNPackage.Name = "BTNPackage";
            this.BTNPackage.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BTNPackage.OnDisabledState.BorderRadius = 1;
            this.BTNPackage.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNPackage.OnDisabledState.BorderThickness = 1;
            this.BTNPackage.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BTNPackage.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BTNPackage.OnDisabledState.IconLeftImage = null;
            this.BTNPackage.OnDisabledState.IconRightImage = null;
            this.BTNPackage.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BTNPackage.onHoverState.BorderRadius = 1;
            this.BTNPackage.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNPackage.onHoverState.BorderThickness = 1;
            this.BTNPackage.onHoverState.FillColor = System.Drawing.Color.Yellow;
            this.BTNPackage.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BTNPackage.onHoverState.IconLeftImage = null;
            this.BTNPackage.onHoverState.IconRightImage = null;
            this.BTNPackage.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BTNPackage.OnIdleState.BorderRadius = 1;
            this.BTNPackage.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.BTNPackage.OnIdleState.BorderThickness = 1;
            this.BTNPackage.OnIdleState.FillColor = System.Drawing.Color.White;
            this.BTNPackage.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.BTNPackage.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("BTNPackage.OnIdleState.IconLeftImage")));
            this.BTNPackage.OnIdleState.IconRightImage = null;
            this.BTNPackage.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BTNPackage.OnPressedState.BorderRadius = 1;
            this.BTNPackage.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNPackage.OnPressedState.BorderThickness = 1;
            this.BTNPackage.OnPressedState.FillColor = System.Drawing.Color.Gold;
            this.BTNPackage.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BTNPackage.OnPressedState.IconLeftImage = null;
            this.BTNPackage.OnPressedState.IconRightImage = null;
            this.BTNPackage.Size = new System.Drawing.Size(267, 53);
            this.BTNPackage.TabIndex = 11;
            this.BTNPackage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BTNPackage.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BTNPackage.TextMarginLeft = 0;
            this.BTNPackage.TextPadding = new System.Windows.Forms.Padding(0);
            this.BTNPackage.UseDefaultRadiusAndThickness = true;
            this.BTNPackage.Click += new System.EventHandler(this.BTNPackage_Click);
            // 
            // BTNVendeur
            // 
            this.BTNVendeur.AllowAnimations = true;
            this.BTNVendeur.AllowMouseEffects = true;
            this.BTNVendeur.AllowToggling = false;
            this.BTNVendeur.AnimationSpeed = 200;
            this.BTNVendeur.AutoGenerateColors = false;
            this.BTNVendeur.AutoRoundBorders = false;
            this.BTNVendeur.AutoSizeLeftIcon = true;
            this.BTNVendeur.AutoSizeRightIcon = true;
            this.BTNVendeur.BackColor = System.Drawing.Color.Transparent;
            this.BTNVendeur.BackColor1 = System.Drawing.Color.White;
            this.BTNVendeur.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BTNVendeur.BackgroundImage")));
            this.BTNVendeur.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.BTNVendeur.ButtonText = "Vendeur";
            this.BTNVendeur.ButtonTextMarginLeft = 0;
            this.BTNVendeur.ColorContrastOnClick = 45;
            this.BTNVendeur.ColorContrastOnHover = 45;
            this.BTNVendeur.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.BTNVendeur.CustomizableEdges = borderEdges7;
            this.BTNVendeur.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BTNVendeur.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BTNVendeur.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BTNVendeur.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BTNVendeur.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BTNVendeur.Font = new System.Drawing.Font("Agency FB", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BTNVendeur.ForeColor = System.Drawing.Color.DimGray;
            this.BTNVendeur.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BTNVendeur.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BTNVendeur.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BTNVendeur.IconMarginLeft = 11;
            this.BTNVendeur.IconPadding = 10;
            this.BTNVendeur.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BTNVendeur.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BTNVendeur.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BTNVendeur.IconSize = 25;
            this.BTNVendeur.IdleBorderColor = System.Drawing.Color.Transparent;
            this.BTNVendeur.IdleBorderRadius = 1;
            this.BTNVendeur.IdleBorderThickness = 1;
            this.BTNVendeur.IdleFillColor = System.Drawing.Color.White;
            this.BTNVendeur.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("BTNVendeur.IdleIconLeftImage")));
            this.BTNVendeur.IdleIconRightImage = null;
            this.BTNVendeur.IndicateFocus = false;
            this.BTNVendeur.Location = new System.Drawing.Point(0, 345);
            this.BTNVendeur.Name = "BTNVendeur";
            this.BTNVendeur.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BTNVendeur.OnDisabledState.BorderRadius = 1;
            this.BTNVendeur.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNVendeur.OnDisabledState.BorderThickness = 1;
            this.BTNVendeur.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BTNVendeur.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BTNVendeur.OnDisabledState.IconLeftImage = null;
            this.BTNVendeur.OnDisabledState.IconRightImage = null;
            this.BTNVendeur.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BTNVendeur.onHoverState.BorderRadius = 1;
            this.BTNVendeur.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNVendeur.onHoverState.BorderThickness = 1;
            this.BTNVendeur.onHoverState.FillColor = System.Drawing.Color.Salmon;
            this.BTNVendeur.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BTNVendeur.onHoverState.IconLeftImage = null;
            this.BTNVendeur.onHoverState.IconRightImage = null;
            this.BTNVendeur.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BTNVendeur.OnIdleState.BorderRadius = 1;
            this.BTNVendeur.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.BTNVendeur.OnIdleState.BorderThickness = 1;
            this.BTNVendeur.OnIdleState.FillColor = System.Drawing.Color.White;
            this.BTNVendeur.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.BTNVendeur.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("BTNVendeur.OnIdleState.IconLeftImage")));
            this.BTNVendeur.OnIdleState.IconRightImage = null;
            this.BTNVendeur.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BTNVendeur.OnPressedState.BorderRadius = 1;
            this.BTNVendeur.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNVendeur.OnPressedState.BorderThickness = 1;
            this.BTNVendeur.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BTNVendeur.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BTNVendeur.OnPressedState.IconLeftImage = null;
            this.BTNVendeur.OnPressedState.IconRightImage = null;
            this.BTNVendeur.Size = new System.Drawing.Size(267, 53);
            this.BTNVendeur.TabIndex = 10;
            this.BTNVendeur.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BTNVendeur.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BTNVendeur.TextMarginLeft = 0;
            this.BTNVendeur.TextPadding = new System.Windows.Forms.Padding(0);
            this.BTNVendeur.UseDefaultRadiusAndThickness = true;
            this.BTNVendeur.Click += new System.EventHandler(this.BTNVendeur_Click);
            // 
            // BTNEntraineur
            // 
            this.BTNEntraineur.AllowAnimations = true;
            this.BTNEntraineur.AllowMouseEffects = true;
            this.BTNEntraineur.AllowToggling = false;
            this.BTNEntraineur.AnimationSpeed = 200;
            this.BTNEntraineur.AutoGenerateColors = false;
            this.BTNEntraineur.AutoRoundBorders = false;
            this.BTNEntraineur.AutoSizeLeftIcon = true;
            this.BTNEntraineur.AutoSizeRightIcon = true;
            this.BTNEntraineur.BackColor = System.Drawing.Color.Transparent;
            this.BTNEntraineur.BackColor1 = System.Drawing.Color.White;
            this.BTNEntraineur.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BTNEntraineur.BackgroundImage")));
            this.BTNEntraineur.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.BTNEntraineur.ButtonText = "Entraîneurs";
            this.BTNEntraineur.ButtonTextMarginLeft = 0;
            this.BTNEntraineur.ColorContrastOnClick = 45;
            this.BTNEntraineur.ColorContrastOnHover = 45;
            this.BTNEntraineur.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.BTNEntraineur.CustomizableEdges = borderEdges8;
            this.BTNEntraineur.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BTNEntraineur.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BTNEntraineur.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BTNEntraineur.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BTNEntraineur.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BTNEntraineur.Font = new System.Drawing.Font("Agency FB", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BTNEntraineur.ForeColor = System.Drawing.Color.DimGray;
            this.BTNEntraineur.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BTNEntraineur.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BTNEntraineur.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BTNEntraineur.IconMarginLeft = 11;
            this.BTNEntraineur.IconPadding = 10;
            this.BTNEntraineur.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BTNEntraineur.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BTNEntraineur.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BTNEntraineur.IconSize = 25;
            this.BTNEntraineur.IdleBorderColor = System.Drawing.Color.Transparent;
            this.BTNEntraineur.IdleBorderRadius = 1;
            this.BTNEntraineur.IdleBorderThickness = 1;
            this.BTNEntraineur.IdleFillColor = System.Drawing.Color.White;
            this.BTNEntraineur.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("BTNEntraineur.IdleIconLeftImage")));
            this.BTNEntraineur.IdleIconRightImage = null;
            this.BTNEntraineur.IndicateFocus = false;
            this.BTNEntraineur.Location = new System.Drawing.Point(0, 227);
            this.BTNEntraineur.Name = "BTNEntraineur";
            this.BTNEntraineur.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BTNEntraineur.OnDisabledState.BorderRadius = 1;
            this.BTNEntraineur.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNEntraineur.OnDisabledState.BorderThickness = 1;
            this.BTNEntraineur.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BTNEntraineur.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BTNEntraineur.OnDisabledState.IconLeftImage = null;
            this.BTNEntraineur.OnDisabledState.IconRightImage = null;
            this.BTNEntraineur.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BTNEntraineur.onHoverState.BorderRadius = 1;
            this.BTNEntraineur.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNEntraineur.onHoverState.BorderThickness = 1;
            this.BTNEntraineur.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.BTNEntraineur.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BTNEntraineur.onHoverState.IconLeftImage = null;
            this.BTNEntraineur.onHoverState.IconRightImage = null;
            this.BTNEntraineur.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BTNEntraineur.OnIdleState.BorderRadius = 1;
            this.BTNEntraineur.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.BTNEntraineur.OnIdleState.BorderThickness = 1;
            this.BTNEntraineur.OnIdleState.FillColor = System.Drawing.Color.White;
            this.BTNEntraineur.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.BTNEntraineur.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("BTNEntraineur.OnIdleState.IconLeftImage")));
            this.BTNEntraineur.OnIdleState.IconRightImage = null;
            this.BTNEntraineur.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BTNEntraineur.OnPressedState.BorderRadius = 1;
            this.BTNEntraineur.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNEntraineur.OnPressedState.BorderThickness = 1;
            this.BTNEntraineur.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BTNEntraineur.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BTNEntraineur.OnPressedState.IconLeftImage = null;
            this.BTNEntraineur.OnPressedState.IconRightImage = null;
            this.BTNEntraineur.Size = new System.Drawing.Size(267, 53);
            this.BTNEntraineur.TabIndex = 8;
            this.BTNEntraineur.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BTNEntraineur.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BTNEntraineur.TextMarginLeft = 0;
            this.BTNEntraineur.TextPadding = new System.Windows.Forms.Padding(0);
            this.BTNEntraineur.UseDefaultRadiusAndThickness = true;
            this.BTNEntraineur.Click += new System.EventHandler(this.BTNEntraineur_Click);
            // 
            // BTNMembre
            // 
            this.BTNMembre.AllowAnimations = true;
            this.BTNMembre.AllowMouseEffects = true;
            this.BTNMembre.AllowToggling = false;
            this.BTNMembre.AnimationSpeed = 200;
            this.BTNMembre.AutoGenerateColors = false;
            this.BTNMembre.AutoRoundBorders = false;
            this.BTNMembre.AutoSizeLeftIcon = true;
            this.BTNMembre.AutoSizeRightIcon = true;
            this.BTNMembre.BackColor = System.Drawing.Color.Transparent;
            this.BTNMembre.BackColor1 = System.Drawing.Color.White;
            this.BTNMembre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BTNMembre.BackgroundImage")));
            this.BTNMembre.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.BTNMembre.ButtonText = "Membership";
            this.BTNMembre.ButtonTextMarginLeft = 0;
            this.BTNMembre.ColorContrastOnClick = 45;
            this.BTNMembre.ColorContrastOnHover = 45;
            this.BTNMembre.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.BTNMembre.CustomizableEdges = borderEdges9;
            this.BTNMembre.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BTNMembre.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BTNMembre.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BTNMembre.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BTNMembre.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BTNMembre.Font = new System.Drawing.Font("Agency FB", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BTNMembre.ForeColor = System.Drawing.Color.DimGray;
            this.BTNMembre.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BTNMembre.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BTNMembre.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BTNMembre.IconMarginLeft = 11;
            this.BTNMembre.IconPadding = 10;
            this.BTNMembre.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BTNMembre.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BTNMembre.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BTNMembre.IconSize = 25;
            this.BTNMembre.IdleBorderColor = System.Drawing.Color.Transparent;
            this.BTNMembre.IdleBorderRadius = 1;
            this.BTNMembre.IdleBorderThickness = 1;
            this.BTNMembre.IdleFillColor = System.Drawing.Color.White;
            this.BTNMembre.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("BTNMembre.IdleIconLeftImage")));
            this.BTNMembre.IdleIconRightImage = null;
            this.BTNMembre.IndicateFocus = false;
            this.BTNMembre.Location = new System.Drawing.Point(0, 175);
            this.BTNMembre.Name = "BTNMembre";
            this.BTNMembre.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BTNMembre.OnDisabledState.BorderRadius = 1;
            this.BTNMembre.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNMembre.OnDisabledState.BorderThickness = 1;
            this.BTNMembre.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BTNMembre.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BTNMembre.OnDisabledState.IconLeftImage = null;
            this.BTNMembre.OnDisabledState.IconRightImage = null;
            this.BTNMembre.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BTNMembre.onHoverState.BorderRadius = 1;
            this.BTNMembre.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNMembre.onHoverState.BorderThickness = 1;
            this.BTNMembre.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BTNMembre.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BTNMembre.onHoverState.IconLeftImage = null;
            this.BTNMembre.onHoverState.IconRightImage = null;
            this.BTNMembre.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BTNMembre.OnIdleState.BorderRadius = 1;
            this.BTNMembre.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.BTNMembre.OnIdleState.BorderThickness = 1;
            this.BTNMembre.OnIdleState.FillColor = System.Drawing.Color.White;
            this.BTNMembre.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.BTNMembre.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("BTNMembre.OnIdleState.IconLeftImage")));
            this.BTNMembre.OnIdleState.IconRightImage = null;
            this.BTNMembre.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BTNMembre.OnPressedState.BorderRadius = 1;
            this.BTNMembre.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNMembre.OnPressedState.BorderThickness = 1;
            this.BTNMembre.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BTNMembre.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BTNMembre.OnPressedState.IconLeftImage = null;
            this.BTNMembre.OnPressedState.IconRightImage = null;
            this.BTNMembre.Size = new System.Drawing.Size(267, 53);
            this.BTNMembre.TabIndex = 7;
            this.BTNMembre.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BTNMembre.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BTNMembre.TextMarginLeft = 0;
            this.BTNMembre.TextPadding = new System.Windows.Forms.Padding(0);
            this.BTNMembre.UseDefaultRadiusAndThickness = true;
            this.BTNMembre.Click += new System.EventHandler(this.BTNMembre_Click);
            // 
            // BTNstatistique
            // 
            this.BTNstatistique.AllowAnimations = true;
            this.BTNstatistique.AllowMouseEffects = true;
            this.BTNstatistique.AllowToggling = false;
            this.BTNstatistique.AnimationSpeed = 200;
            this.BTNstatistique.AutoGenerateColors = false;
            this.BTNstatistique.AutoRoundBorders = false;
            this.BTNstatistique.AutoSizeLeftIcon = true;
            this.BTNstatistique.AutoSizeRightIcon = true;
            this.BTNstatistique.BackColor = System.Drawing.Color.Transparent;
            this.BTNstatistique.BackColor1 = System.Drawing.Color.White;
            this.BTNstatistique.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BTNstatistique.BackgroundImage")));
            this.BTNstatistique.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.BTNstatistique.ButtonText = "statistiques";
            this.BTNstatistique.ButtonTextMarginLeft = 0;
            this.BTNstatistique.ColorContrastOnClick = 45;
            this.BTNstatistique.ColorContrastOnHover = 45;
            this.BTNstatistique.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.BTNstatistique.CustomizableEdges = borderEdges10;
            this.BTNstatistique.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BTNstatistique.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BTNstatistique.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BTNstatistique.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BTNstatistique.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BTNstatistique.Font = new System.Drawing.Font("Agency FB", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BTNstatistique.ForeColor = System.Drawing.Color.DimGray;
            this.BTNstatistique.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BTNstatistique.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BTNstatistique.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BTNstatistique.IconMarginLeft = 11;
            this.BTNstatistique.IconPadding = 10;
            this.BTNstatistique.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BTNstatistique.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BTNstatistique.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BTNstatistique.IconSize = 25;
            this.BTNstatistique.IdleBorderColor = System.Drawing.Color.Transparent;
            this.BTNstatistique.IdleBorderRadius = 1;
            this.BTNstatistique.IdleBorderThickness = 1;
            this.BTNstatistique.IdleFillColor = System.Drawing.Color.White;
            this.BTNstatistique.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("BTNstatistique.IdleIconLeftImage")));
            this.BTNstatistique.IdleIconRightImage = null;
            this.BTNstatistique.IndicateFocus = false;
            this.BTNstatistique.Location = new System.Drawing.Point(0, 123);
            this.BTNstatistique.Name = "BTNstatistique";
            this.BTNstatistique.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BTNstatistique.OnDisabledState.BorderRadius = 1;
            this.BTNstatistique.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNstatistique.OnDisabledState.BorderThickness = 1;
            this.BTNstatistique.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BTNstatistique.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BTNstatistique.OnDisabledState.IconLeftImage = null;
            this.BTNstatistique.OnDisabledState.IconRightImage = null;
            this.BTNstatistique.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BTNstatistique.onHoverState.BorderRadius = 1;
            this.BTNstatistique.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNstatistique.onHoverState.BorderThickness = 1;
            this.BTNstatistique.onHoverState.FillColor = System.Drawing.Color.Chocolate;
            this.BTNstatistique.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BTNstatistique.onHoverState.IconLeftImage = null;
            this.BTNstatistique.onHoverState.IconRightImage = null;
            this.BTNstatistique.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BTNstatistique.OnIdleState.BorderRadius = 1;
            this.BTNstatistique.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.BTNstatistique.OnIdleState.BorderThickness = 1;
            this.BTNstatistique.OnIdleState.FillColor = System.Drawing.Color.White;
            this.BTNstatistique.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.BTNstatistique.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("BTNstatistique.OnIdleState.IconLeftImage")));
            this.BTNstatistique.OnIdleState.IconRightImage = null;
            this.BTNstatistique.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BTNstatistique.OnPressedState.BorderRadius = 1;
            this.BTNstatistique.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BTNstatistique.OnPressedState.BorderThickness = 1;
            this.BTNstatistique.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BTNstatistique.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BTNstatistique.OnPressedState.IconLeftImage = null;
            this.BTNstatistique.OnPressedState.IconRightImage = null;
            this.BTNstatistique.Size = new System.Drawing.Size(267, 53);
            this.BTNstatistique.TabIndex = 6;
            this.BTNstatistique.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BTNstatistique.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BTNstatistique.TextMarginLeft = 0;
            this.BTNstatistique.TextPadding = new System.Windows.Forms.Padding(0);
            this.BTNstatistique.UseDefaultRadiusAndThickness = true;
            this.BTNstatistique.Click += new System.EventHandler(this.BTNstatistique_Click);
            // 
            // BTNfermer
            // 
            this.BTNfermer.BackColor = System.Drawing.Color.Transparent;
            this.BTNfermer.color = System.Drawing.Color.Transparent;
            this.BTNfermer.colorActive = System.Drawing.Color.Red;
            this.BTNfermer.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BTNfermer.Font = new System.Drawing.Font("Century Gothic", 15.75F);
            this.BTNfermer.ForeColor = System.Drawing.Color.White;
            this.BTNfermer.Image = ((System.Drawing.Image)(resources.GetObject("BTNfermer.Image")));
            this.BTNfermer.ImagePosition = 5;
            this.BTNfermer.ImageZoom = 80;
            this.BTNfermer.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.BTNfermer.LabelPosition = 0;
            this.BTNfermer.LabelText = "";
            this.BTNfermer.Location = new System.Drawing.Point(1322, 0);
            this.BTNfermer.Margin = new System.Windows.Forms.Padding(6);
            this.BTNfermer.Name = "BTNfermer";
            this.BTNfermer.Size = new System.Drawing.Size(46, 46);
            this.BTNfermer.TabIndex = 12;
            this.BTNfermer.Click += new System.EventHandler(this.BTNfermer_Click);
            // 
            // BTNredire
            // 
            this.BTNredire.BackColor = System.Drawing.Color.Transparent;
            this.BTNredire.color = System.Drawing.Color.Transparent;
            this.BTNredire.colorActive = System.Drawing.Color.Thistle;
            this.BTNredire.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BTNredire.Font = new System.Drawing.Font("Century Gothic", 15.75F);
            this.BTNredire.ForeColor = System.Drawing.Color.White;
            this.BTNredire.Image = ((System.Drawing.Image)(resources.GetObject("BTNredire.Image")));
            this.BTNredire.ImagePosition = 5;
            this.BTNredire.ImageZoom = 80;
            this.BTNredire.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.BTNredire.LabelPosition = 0;
            this.BTNredire.LabelText = "";
            this.BTNredire.Location = new System.Drawing.Point(1255, 0);
            this.BTNredire.Margin = new System.Windows.Forms.Padding(6);
            this.BTNredire.Name = "BTNredire";
            this.BTNredire.Size = new System.Drawing.Size(49, 45);
            this.BTNredire.TabIndex = 13;
            this.BTNredire.Click += new System.EventHandler(this.BTNredire_Click);
            // 
            // Panel2
            // 
            this.Panel2.BackgroundColor = System.Drawing.Color.Purple;
            this.Panel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Panel2.BackgroundImage")));
            this.Panel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.Panel2.BorderColor = System.Drawing.Color.Transparent;
            this.Panel2.BorderRadius = 3;
            this.Panel2.BorderThickness = 1;
            this.Panel2.Controls.Add(this.BTNredire);
            this.Panel2.Controls.Add(this.BTNfermer);
            this.Panel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.Panel2.Location = new System.Drawing.Point(0, 0);
            this.Panel2.Name = "Panel2";
            this.Panel2.ShowBorders = true;
            this.Panel2.Size = new System.Drawing.Size(1367, 46);
            this.Panel2.TabIndex = 155;
            this.Panel2.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Panel2_MouseDown);
            // 
            // PAnelDesktop
            // 
            this.PAnelDesktop.BackgroundColor = System.Drawing.Color.White;
            this.PAnelDesktop.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PAnelDesktop.BackgroundImage")));
            this.PAnelDesktop.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.PAnelDesktop.BorderColor = System.Drawing.Color.Transparent;
            this.PAnelDesktop.BorderRadius = 3;
            this.PAnelDesktop.BorderThickness = 1;
            this.PAnelDesktop.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PAnelDesktop.Location = new System.Drawing.Point(267, 46);
            this.PAnelDesktop.Name = "PAnelDesktop";
            this.PAnelDesktop.ShowBorders = true;
            this.PAnelDesktop.Size = new System.Drawing.Size(1100, 755);
            this.PAnelDesktop.TabIndex = 160;
            this.PAnelDesktop.Click += new System.EventHandler(this.PAnelDesktop_Click);
            // 
            // FormGestionnaire
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1367, 801);
            this.Controls.Add(this.PAnelDesktop);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.Panel2);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormGestionnaire";
            this.Text = "FormGestionnaire";
            this.Load += new System.EventHandler(this.FormGestionnaire_Load);
            this.bunifuPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.Panel2.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BTNPrésence;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnPaiment;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BTNPackage;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BTNVendeur;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BTNEntraineur;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BTNMembre;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BTNstatistique;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BTNutilisateur;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BTNQuitter;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BTNAchat;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuPanel Panel2;
        private Bunifu.Framework.UI.BunifuTileButton BTNredire;
        private Bunifu.Framework.UI.BunifuTileButton BTNfermer;
        private Bunifu.UI.WinForms.BunifuPanel PAnelDesktop;
    }
}