
namespace Centre_D_affaire.GestionSalleDeSport
{
    partial class UCgetionAchats
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UCgetionAchats));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.lblnumero = new System.Windows.Forms.Label();
            this.DPdate = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.lblNOms = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.TXTnumero = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TXTtele = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TXTnomcomplet = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.GriAchat = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.NomProduit = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Prix = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Total = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.label10 = new System.Windows.Forms.Label();
            this.TXTProduitNom = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.txtTotal = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.TXTquantite = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.TXTprix = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnAcheter = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btntrouver = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuTextBox3 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label9 = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.GriAchat)).BeginInit();
            this.SuspendLayout();
            // 
            // lblnumero
            // 
            this.lblnumero.AutoSize = true;
            this.lblnumero.BackColor = System.Drawing.Color.Transparent;
            this.lblnumero.Font = new System.Drawing.Font("Ink Free", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblnumero.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblnumero.Location = new System.Drawing.Point(25, 330);
            this.lblnumero.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblnumero.Name = "lblnumero";
            this.lblnumero.Size = new System.Drawing.Size(112, 27);
            this.lblnumero.TabIndex = 248;
            this.lblnumero.Text = "Achat ID";
            // 
            // DPdate
            // 
            this.DPdate.BackColor = System.Drawing.Color.Transparent;
            this.DPdate.BorderRadius = 17;
            this.DPdate.CalendarForeColor = System.Drawing.Color.Brown;
            this.DPdate.CalendarTitleBackColor = System.Drawing.Color.Maroon;
            this.DPdate.Color = System.Drawing.Color.Silver;
            this.DPdate.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.DPdate.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.DPdate.DisabledColor = System.Drawing.Color.Gray;
            this.DPdate.DisplayWeekNumbers = false;
            this.DPdate.DPHeight = 0;
            this.DPdate.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.DPdate.FillDatePicker = false;
            this.DPdate.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.DPdate.ForeColor = System.Drawing.Color.Brown;
            this.DPdate.Icon = ((System.Drawing.Image)(resources.GetObject("DPdate.Icon")));
            this.DPdate.IconColor = System.Drawing.Color.Gray;
            this.DPdate.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.DPdate.LeftTextMargin = 5;
            this.DPdate.Location = new System.Drawing.Point(229, 323);
            this.DPdate.MinimumSize = new System.Drawing.Size(4, 32);
            this.DPdate.Name = "DPdate";
            this.DPdate.Size = new System.Drawing.Size(224, 32);
            this.DPdate.TabIndex = 255;
            this.DPdate.Value = new System.DateTime(2021, 5, 14, 0, 0, 0, 0);
            // 
            // lblNOms
            // 
            this.lblNOms.AutoSize = true;
            this.lblNOms.BackColor = System.Drawing.Color.Transparent;
            this.lblNOms.Font = new System.Drawing.Font("Ink Free", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblNOms.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblNOms.Location = new System.Drawing.Point(55, 36);
            this.lblNOms.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblNOms.Name = "lblNOms";
            this.lblNOms.Size = new System.Drawing.Size(129, 27);
            this.lblNOms.TabIndex = 249;
            this.lblNOms.Text = "ID Vendeur";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Ink Free", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label2.Location = new System.Drawing.Point(224, 293);
            this.label2.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(132, 27);
            this.label2.TabIndex = 254;
            this.label2.Text = "Date Achat";
            // 
            // TXTnumero
            // 
            this.TXTnumero.AcceptsReturn = false;
            this.TXTnumero.AcceptsTab = false;
            this.TXTnumero.AnimationSpeed = 200;
            this.TXTnumero.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TXTnumero.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TXTnumero.BackColor = System.Drawing.Color.White;
            this.TXTnumero.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TXTnumero.BackgroundImage")));
            this.TXTnumero.BorderColorActive = System.Drawing.Color.DarkMagenta;
            this.TXTnumero.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TXTnumero.BorderColorHover = System.Drawing.Color.Magenta;
            this.TXTnumero.BorderColorIdle = System.Drawing.Color.Maroon;
            this.TXTnumero.BorderRadius = 1;
            this.TXTnumero.BorderThickness = 4;
            this.TXTnumero.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TXTnumero.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TXTnumero.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TXTnumero.DefaultText = "";
            this.TXTnumero.FillColor = System.Drawing.Color.White;
            this.TXTnumero.HideSelection = true;
            this.TXTnumero.IconLeft = null;
            this.TXTnumero.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TXTnumero.IconPadding = 10;
            this.TXTnumero.IconRight = null;
            this.TXTnumero.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TXTnumero.Lines = new string[0];
            this.TXTnumero.Location = new System.Drawing.Point(30, 360);
            this.TXTnumero.MaxLength = 32767;
            this.TXTnumero.MinimumSize = new System.Drawing.Size(1, 1);
            this.TXTnumero.Modified = false;
            this.TXTnumero.Multiline = false;
            this.TXTnumero.Name = "TXTnumero";
            stateProperties1.BorderColor = System.Drawing.Color.DarkMagenta;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TXTnumero.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TXTnumero.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Magenta;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TXTnumero.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Maroon;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TXTnumero.OnIdleState = stateProperties4;
            this.TXTnumero.Padding = new System.Windows.Forms.Padding(3);
            this.TXTnumero.PasswordChar = '\0';
            this.TXTnumero.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TXTnumero.PlaceholderText = "Tapez ici ";
            this.TXTnumero.ReadOnly = false;
            this.TXTnumero.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TXTnumero.SelectedText = "";
            this.TXTnumero.SelectionLength = 0;
            this.TXTnumero.SelectionStart = 0;
            this.TXTnumero.ShortcutsEnabled = true;
            this.TXTnumero.Size = new System.Drawing.Size(166, 40);
            this.TXTnumero.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TXTnumero.TabIndex = 250;
            this.TXTnumero.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TXTnumero.TextMarginBottom = 0;
            this.TXTnumero.TextMarginLeft = -9;
            this.TXTnumero.TextMarginTop = 0;
            this.TXTnumero.TextPlaceholder = "Tapez ici ";
            this.TXTnumero.UseSystemPasswordChar = false;
            this.TXTnumero.WordWrap = true;
            // 
            // TXTtele
            // 
            this.TXTtele.AcceptsReturn = false;
            this.TXTtele.AcceptsTab = false;
            this.TXTtele.AnimationSpeed = 200;
            this.TXTtele.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TXTtele.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TXTtele.AutoSize = true;
            this.TXTtele.BackColor = System.Drawing.Color.White;
            this.TXTtele.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TXTtele.BackgroundImage")));
            this.TXTtele.BorderColorActive = System.Drawing.Color.DarkMagenta;
            this.TXTtele.BorderColorDisabled = System.Drawing.Color.Azure;
            this.TXTtele.BorderColorHover = System.Drawing.Color.Magenta;
            this.TXTtele.BorderColorIdle = System.Drawing.Color.Maroon;
            this.TXTtele.BorderRadius = 1;
            this.TXTtele.BorderThickness = 4;
            this.TXTtele.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TXTtele.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TXTtele.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TXTtele.DefaultText = "";
            this.TXTtele.FillColor = System.Drawing.Color.White;
            this.TXTtele.HideSelection = true;
            this.TXTtele.IconLeft = null;
            this.TXTtele.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TXTtele.IconPadding = 10;
            this.TXTtele.IconRight = null;
            this.TXTtele.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TXTtele.Lines = new string[0];
            this.TXTtele.Location = new System.Drawing.Point(561, 66);
            this.TXTtele.MaxLength = 32767;
            this.TXTtele.MinimumSize = new System.Drawing.Size(1, 1);
            this.TXTtele.Modified = false;
            this.TXTtele.Multiline = false;
            this.TXTtele.Name = "TXTtele";
            stateProperties5.BorderColor = System.Drawing.Color.DarkMagenta;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TXTtele.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Azure;
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TXTtele.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.Magenta;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TXTtele.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Maroon;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TXTtele.OnIdleState = stateProperties8;
            this.TXTtele.Padding = new System.Windows.Forms.Padding(3);
            this.TXTtele.PasswordChar = '\0';
            this.TXTtele.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TXTtele.PlaceholderText = "Tapez ici ";
            this.TXTtele.ReadOnly = false;
            this.TXTtele.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TXTtele.SelectedText = "";
            this.TXTtele.SelectionLength = 0;
            this.TXTtele.SelectionStart = 0;
            this.TXTtele.ShortcutsEnabled = true;
            this.TXTtele.Size = new System.Drawing.Size(272, 41);
            this.TXTtele.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TXTtele.TabIndex = 253;
            this.TXTtele.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TXTtele.TextMarginBottom = 0;
            this.TXTtele.TextMarginLeft = -9;
            this.TXTtele.TextMarginTop = 0;
            this.TXTtele.TextPlaceholder = "Tapez ici ";
            this.TXTtele.UseSystemPasswordChar = false;
            this.TXTtele.WordWrap = true;
            // 
            // TXTnomcomplet
            // 
            this.TXTnomcomplet.AcceptsReturn = false;
            this.TXTnomcomplet.AcceptsTab = false;
            this.TXTnomcomplet.AnimationSpeed = 200;
            this.TXTnomcomplet.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TXTnomcomplet.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TXTnomcomplet.BackColor = System.Drawing.Color.White;
            this.TXTnomcomplet.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TXTnomcomplet.BackgroundImage")));
            this.TXTnomcomplet.BorderColorActive = System.Drawing.Color.DarkMagenta;
            this.TXTnomcomplet.BorderColorDisabled = System.Drawing.Color.Azure;
            this.TXTnomcomplet.BorderColorHover = System.Drawing.Color.Magenta;
            this.TXTnomcomplet.BorderColorIdle = System.Drawing.Color.Maroon;
            this.TXTnomcomplet.BorderRadius = 1;
            this.TXTnomcomplet.BorderThickness = 4;
            this.TXTnomcomplet.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TXTnomcomplet.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TXTnomcomplet.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TXTnomcomplet.DefaultText = "";
            this.TXTnomcomplet.FillColor = System.Drawing.Color.White;
            this.TXTnomcomplet.HideSelection = true;
            this.TXTnomcomplet.IconLeft = null;
            this.TXTnomcomplet.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TXTnomcomplet.IconPadding = 10;
            this.TXTnomcomplet.IconRight = null;
            this.TXTnomcomplet.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TXTnomcomplet.Lines = new string[0];
            this.TXTnomcomplet.Location = new System.Drawing.Point(60, 66);
            this.TXTnomcomplet.MaxLength = 32767;
            this.TXTnomcomplet.MinimumSize = new System.Drawing.Size(1, 1);
            this.TXTnomcomplet.Modified = false;
            this.TXTnomcomplet.Multiline = false;
            this.TXTnomcomplet.Name = "TXTnomcomplet";
            stateProperties9.BorderColor = System.Drawing.Color.DarkMagenta;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TXTnomcomplet.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Azure;
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TXTnomcomplet.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Magenta;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TXTnomcomplet.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Maroon;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TXTnomcomplet.OnIdleState = stateProperties12;
            this.TXTnomcomplet.Padding = new System.Windows.Forms.Padding(3);
            this.TXTnomcomplet.PasswordChar = '\0';
            this.TXTnomcomplet.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TXTnomcomplet.PlaceholderText = "Tapez ici ";
            this.TXTnomcomplet.ReadOnly = false;
            this.TXTnomcomplet.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TXTnomcomplet.SelectedText = "";
            this.TXTnomcomplet.SelectionLength = 0;
            this.TXTnomcomplet.SelectionStart = 0;
            this.TXTnomcomplet.ShortcutsEnabled = true;
            this.TXTnomcomplet.Size = new System.Drawing.Size(272, 41);
            this.TXTnomcomplet.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TXTnomcomplet.TabIndex = 251;
            this.TXTnomcomplet.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TXTnomcomplet.TextMarginBottom = 0;
            this.TXTnomcomplet.TextMarginLeft = -9;
            this.TXTnomcomplet.TextMarginTop = 0;
            this.TXTnomcomplet.TextPlaceholder = "Tapez ici ";
            this.TXTnomcomplet.UseSystemPasswordChar = false;
            this.TXTnomcomplet.WordWrap = true;
            this.TXTnomcomplet.TextChanged += new System.EventHandler(this.TXTnomcomplet_TextChanged);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Ink Free", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label1.Location = new System.Drawing.Point(556, 22);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(113, 27);
            this.label1.TabIndex = 252;
            this.label1.Text = "Téléphone";
            // 
            // GriAchat
            // 
            this.GriAchat.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.GriAchat.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.GriAchat.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.GriAchat.BackgroundColor = System.Drawing.SystemColors.ButtonHighlight;
            this.GriAchat.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.GriAchat.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.GriAchat.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.Maroon;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.GriAchat.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.GriAchat.ColumnHeadersHeight = 40;
            this.GriAchat.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.NomProduit,
            this.Prix,
            this.Total});
            this.GriAchat.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.GriAchat.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.GriAchat.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.GriAchat.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(102)))), ((int)(((byte)(102)))));
            this.GriAchat.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
            this.GriAchat.CurrentTheme.BackColor = System.Drawing.Color.Maroon;
            this.GriAchat.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(178)))), ((int)(((byte)(178)))));
            this.GriAchat.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.Maroon;
            this.GriAchat.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.GriAchat.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.GriAchat.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.GriAchat.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.GriAchat.CurrentTheme.Name = null;
            this.GriAchat.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(229)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.GriAchat.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.GriAchat.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.GriAchat.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(102)))), ((int)(((byte)(102)))));
            this.GriAchat.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(229)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(102)))), ((int)(((byte)(102)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.GriAchat.DefaultCellStyle = dataGridViewCellStyle3;
            this.GriAchat.EnableHeadersVisualStyles = false;
            this.GriAchat.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(178)))), ((int)(((byte)(178)))));
            this.GriAchat.HeaderBackColor = System.Drawing.Color.Maroon;
            this.GriAchat.HeaderBgColor = System.Drawing.Color.Empty;
            this.GriAchat.HeaderForeColor = System.Drawing.Color.White;
            this.GriAchat.Location = new System.Drawing.Point(30, 409);
            this.GriAchat.Name = "GriAchat";
            this.GriAchat.RowHeadersVisible = false;
            this.GriAchat.RowHeadersWidth = 62;
            this.GriAchat.RowTemplate.Height = 40;
            this.GriAchat.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.GriAchat.Size = new System.Drawing.Size(852, 238);
            this.GriAchat.TabIndex = 267;
            this.GriAchat.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Maroon;
            // 
            // NomProduit
            // 
            this.NomProduit.HeaderText = "Nom du produit";
            this.NomProduit.MinimumWidth = 8;
            this.NomProduit.Name = "NomProduit";
            // 
            // Prix
            // 
            this.Prix.HeaderText = "Prix";
            this.Prix.MinimumWidth = 8;
            this.Prix.Name = "Prix";
            // 
            // Total
            // 
            this.Total.HeaderText = "Total";
            this.Total.MinimumWidth = 8;
            this.Total.Name = "Total";
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.BackColor = System.Drawing.Color.Transparent;
            this.label10.Font = new System.Drawing.Font("Ink Free", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label10.Location = new System.Drawing.Point(457, 373);
            this.label10.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(166, 27);
            this.label10.TabIndex = 266;
            this.label10.Text = "Nom du Produit";
            // 
            // TXTProduitNom
            // 
            this.TXTProduitNom.AcceptsReturn = false;
            this.TXTProduitNom.AcceptsTab = false;
            this.TXTProduitNom.AnimationSpeed = 200;
            this.TXTProduitNom.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TXTProduitNom.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TXTProduitNom.BackColor = System.Drawing.Color.White;
            this.TXTProduitNom.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TXTProduitNom.BackgroundImage")));
            this.TXTProduitNom.BorderColorActive = System.Drawing.Color.DarkMagenta;
            this.TXTProduitNom.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TXTProduitNom.BorderColorHover = System.Drawing.Color.Magenta;
            this.TXTProduitNom.BorderColorIdle = System.Drawing.Color.Maroon;
            this.TXTProduitNom.BorderRadius = 1;
            this.TXTProduitNom.BorderThickness = 4;
            this.TXTProduitNom.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TXTProduitNom.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TXTProduitNom.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TXTProduitNom.DefaultText = "";
            this.TXTProduitNom.FillColor = System.Drawing.Color.White;
            this.TXTProduitNom.HideSelection = true;
            this.TXTProduitNom.IconLeft = null;
            this.TXTProduitNom.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TXTProduitNom.IconPadding = 10;
            this.TXTProduitNom.IconRight = null;
            this.TXTProduitNom.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TXTProduitNom.Lines = new string[0];
            this.TXTProduitNom.Location = new System.Drawing.Point(630, 356);
            this.TXTProduitNom.MaxLength = 32767;
            this.TXTProduitNom.MinimumSize = new System.Drawing.Size(1, 1);
            this.TXTProduitNom.Modified = false;
            this.TXTProduitNom.Multiline = false;
            this.TXTProduitNom.Name = "TXTProduitNom";
            stateProperties13.BorderColor = System.Drawing.Color.DarkMagenta;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TXTProduitNom.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TXTProduitNom.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Magenta;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TXTProduitNom.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Maroon;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TXTProduitNom.OnIdleState = stateProperties16;
            this.TXTProduitNom.Padding = new System.Windows.Forms.Padding(3);
            this.TXTProduitNom.PasswordChar = '\0';
            this.TXTProduitNom.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TXTProduitNom.PlaceholderText = "Tapez ici ";
            this.TXTProduitNom.ReadOnly = false;
            this.TXTProduitNom.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TXTProduitNom.SelectedText = "";
            this.TXTProduitNom.SelectionLength = 0;
            this.TXTProduitNom.SelectionStart = 0;
            this.TXTProduitNom.ShortcutsEnabled = true;
            this.TXTProduitNom.Size = new System.Drawing.Size(272, 40);
            this.TXTProduitNom.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TXTProduitNom.TabIndex = 265;
            this.TXTProduitNom.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TXTProduitNom.TextMarginBottom = 0;
            this.TXTProduitNom.TextMarginLeft = -9;
            this.TXTProduitNom.TextMarginTop = 0;
            this.TXTProduitNom.TextPlaceholder = "Tapez ici ";
            this.TXTProduitNom.UseSystemPasswordChar = false;
            this.TXTProduitNom.WordWrap = true;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.Transparent;
            this.label6.Font = new System.Drawing.Font("Ink Free", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label6.Location = new System.Drawing.Point(909, 554);
            this.label6.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(59, 22);
            this.label6.TabIndex = 262;
            this.label6.Text = "Total";
            // 
            // txtTotal
            // 
            this.txtTotal.AcceptsReturn = false;
            this.txtTotal.AcceptsTab = false;
            this.txtTotal.AnimationSpeed = 200;
            this.txtTotal.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTotal.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTotal.BackColor = System.Drawing.Color.White;
            this.txtTotal.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTotal.BackgroundImage")));
            this.txtTotal.BorderColorActive = System.Drawing.Color.DarkMagenta;
            this.txtTotal.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTotal.BorderColorHover = System.Drawing.Color.Magenta;
            this.txtTotal.BorderColorIdle = System.Drawing.Color.Maroon;
            this.txtTotal.BorderRadius = 1;
            this.txtTotal.BorderThickness = 4;
            this.txtTotal.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTotal.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTotal.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTotal.DefaultText = "";
            this.txtTotal.FillColor = System.Drawing.Color.White;
            this.txtTotal.HideSelection = true;
            this.txtTotal.IconLeft = null;
            this.txtTotal.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTotal.IconPadding = 10;
            this.txtTotal.IconRight = null;
            this.txtTotal.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTotal.Lines = new string[0];
            this.txtTotal.Location = new System.Drawing.Point(914, 574);
            this.txtTotal.MaxLength = 32767;
            this.txtTotal.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTotal.Modified = false;
            this.txtTotal.Multiline = false;
            this.txtTotal.Name = "txtTotal";
            stateProperties17.BorderColor = System.Drawing.Color.DarkMagenta;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTotal.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTotal.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.Magenta;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTotal.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Maroon;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTotal.OnIdleState = stateProperties20;
            this.txtTotal.Padding = new System.Windows.Forms.Padding(3);
            this.txtTotal.PasswordChar = '\0';
            this.txtTotal.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTotal.PlaceholderText = "Tapez ici ";
            this.txtTotal.ReadOnly = false;
            this.txtTotal.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTotal.SelectedText = "";
            this.txtTotal.SelectionLength = 0;
            this.txtTotal.SelectionStart = 0;
            this.txtTotal.ShortcutsEnabled = true;
            this.txtTotal.Size = new System.Drawing.Size(166, 37);
            this.txtTotal.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtTotal.TabIndex = 263;
            this.txtTotal.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTotal.TextMarginBottom = 0;
            this.txtTotal.TextMarginLeft = -9;
            this.txtTotal.TextMarginTop = 0;
            this.txtTotal.TextPlaceholder = "Tapez ici ";
            this.txtTotal.UseSystemPasswordChar = false;
            this.txtTotal.WordWrap = true;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Ink Free", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label4.Location = new System.Drawing.Point(910, 429);
            this.label4.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(88, 22);
            this.label4.TabIndex = 258;
            this.label4.Text = "Quantite";
            // 
            // TXTquantite
            // 
            this.TXTquantite.AcceptsReturn = false;
            this.TXTquantite.AcceptsTab = false;
            this.TXTquantite.AnimationSpeed = 200;
            this.TXTquantite.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TXTquantite.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TXTquantite.BackColor = System.Drawing.Color.White;
            this.TXTquantite.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TXTquantite.BackgroundImage")));
            this.TXTquantite.BorderColorActive = System.Drawing.Color.DarkMagenta;
            this.TXTquantite.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TXTquantite.BorderColorHover = System.Drawing.Color.Magenta;
            this.TXTquantite.BorderColorIdle = System.Drawing.Color.Maroon;
            this.TXTquantite.BorderRadius = 1;
            this.TXTquantite.BorderThickness = 4;
            this.TXTquantite.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TXTquantite.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TXTquantite.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TXTquantite.DefaultText = "";
            this.TXTquantite.FillColor = System.Drawing.Color.White;
            this.TXTquantite.HideSelection = true;
            this.TXTquantite.IconLeft = null;
            this.TXTquantite.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TXTquantite.IconPadding = 10;
            this.TXTquantite.IconRight = null;
            this.TXTquantite.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TXTquantite.Lines = new string[0];
            this.TXTquantite.Location = new System.Drawing.Point(914, 444);
            this.TXTquantite.MaxLength = 32767;
            this.TXTquantite.MinimumSize = new System.Drawing.Size(1, 1);
            this.TXTquantite.Modified = false;
            this.TXTquantite.Multiline = false;
            this.TXTquantite.Name = "TXTquantite";
            stateProperties21.BorderColor = System.Drawing.Color.DarkMagenta;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TXTquantite.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TXTquantite.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.Magenta;
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TXTquantite.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Maroon;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TXTquantite.OnIdleState = stateProperties24;
            this.TXTquantite.Padding = new System.Windows.Forms.Padding(3);
            this.TXTquantite.PasswordChar = '\0';
            this.TXTquantite.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TXTquantite.PlaceholderText = "Tapez ici ";
            this.TXTquantite.ReadOnly = false;
            this.TXTquantite.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TXTquantite.SelectedText = "";
            this.TXTquantite.SelectionLength = 0;
            this.TXTquantite.SelectionStart = 0;
            this.TXTquantite.ShortcutsEnabled = true;
            this.TXTquantite.Size = new System.Drawing.Size(166, 41);
            this.TXTquantite.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TXTquantite.TabIndex = 259;
            this.TXTquantite.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TXTquantite.TextMarginBottom = 0;
            this.TXTquantite.TextMarginLeft = -9;
            this.TXTquantite.TextMarginTop = 0;
            this.TXTquantite.TextPlaceholder = "Tapez ici ";
            this.TXTquantite.UseSystemPasswordChar = false;
            this.TXTquantite.WordWrap = true;
            this.TXTquantite.TextChanged += new System.EventHandler(this.TXTquantite_TextChanged);
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Ink Free", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label3.Location = new System.Drawing.Point(909, 356);
            this.label3.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(51, 27);
            this.label3.TabIndex = 256;
            this.label3.Text = "Prix";
            // 
            // TXTprix
            // 
            this.TXTprix.AcceptsReturn = false;
            this.TXTprix.AcceptsTab = false;
            this.TXTprix.AnimationSpeed = 200;
            this.TXTprix.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TXTprix.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TXTprix.BackColor = System.Drawing.Color.White;
            this.TXTprix.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TXTprix.BackgroundImage")));
            this.TXTprix.BorderColorActive = System.Drawing.Color.DarkMagenta;
            this.TXTprix.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TXTprix.BorderColorHover = System.Drawing.Color.Magenta;
            this.TXTprix.BorderColorIdle = System.Drawing.Color.Maroon;
            this.TXTprix.BorderRadius = 1;
            this.TXTprix.BorderThickness = 4;
            this.TXTprix.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TXTprix.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TXTprix.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TXTprix.DefaultText = "";
            this.TXTprix.FillColor = System.Drawing.Color.White;
            this.TXTprix.HideSelection = true;
            this.TXTprix.IconLeft = null;
            this.TXTprix.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TXTprix.IconPadding = 10;
            this.TXTprix.IconRight = null;
            this.TXTprix.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TXTprix.Lines = new string[0];
            this.TXTprix.Location = new System.Drawing.Point(913, 382);
            this.TXTprix.MaxLength = 32767;
            this.TXTprix.MinimumSize = new System.Drawing.Size(1, 1);
            this.TXTprix.Modified = false;
            this.TXTprix.Multiline = false;
            this.TXTprix.Name = "TXTprix";
            stateProperties25.BorderColor = System.Drawing.Color.DarkMagenta;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TXTprix.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TXTprix.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.Magenta;
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TXTprix.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Maroon;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TXTprix.OnIdleState = stateProperties28;
            this.TXTprix.Padding = new System.Windows.Forms.Padding(3);
            this.TXTprix.PasswordChar = '\0';
            this.TXTprix.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TXTprix.PlaceholderText = "Tapez ici ";
            this.TXTprix.ReadOnly = false;
            this.TXTprix.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TXTprix.SelectedText = "";
            this.TXTprix.SelectionLength = 0;
            this.TXTprix.SelectionStart = 0;
            this.TXTprix.ShortcutsEnabled = true;
            this.TXTprix.Size = new System.Drawing.Size(166, 44);
            this.TXTprix.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TXTprix.TabIndex = 257;
            this.TXTprix.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TXTprix.TextMarginBottom = 0;
            this.TXTprix.TextMarginLeft = -9;
            this.TXTprix.TextMarginTop = 0;
            this.TXTprix.TextPlaceholder = "Tapez ici ";
            this.TXTprix.UseSystemPasswordChar = false;
            this.TXTprix.WordWrap = true;
            // 
            // btnAcheter
            // 
            this.btnAcheter.AllowAnimations = true;
            this.btnAcheter.AllowMouseEffects = true;
            this.btnAcheter.AllowToggling = false;
            this.btnAcheter.AnimationSpeed = 200;
            this.btnAcheter.AutoGenerateColors = false;
            this.btnAcheter.AutoRoundBorders = false;
            this.btnAcheter.AutoSizeLeftIcon = true;
            this.btnAcheter.AutoSizeRightIcon = true;
            this.btnAcheter.BackColor = System.Drawing.Color.Transparent;
            this.btnAcheter.BackColor1 = System.Drawing.Color.IndianRed;
            this.btnAcheter.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAcheter.BackgroundImage")));
            this.btnAcheter.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAcheter.ButtonText = "Acheter";
            this.btnAcheter.ButtonTextMarginLeft = 0;
            this.btnAcheter.ColorContrastOnClick = 45;
            this.btnAcheter.ColorContrastOnHover = 45;
            this.btnAcheter.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnAcheter.CustomizableEdges = borderEdges1;
            this.btnAcheter.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAcheter.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAcheter.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAcheter.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAcheter.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAcheter.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnAcheter.ForeColor = System.Drawing.Color.White;
            this.btnAcheter.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAcheter.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAcheter.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAcheter.IconMarginLeft = 11;
            this.btnAcheter.IconPadding = 10;
            this.btnAcheter.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAcheter.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAcheter.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAcheter.IconSize = 25;
            this.btnAcheter.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnAcheter.IdleBorderRadius = 1;
            this.btnAcheter.IdleBorderThickness = 1;
            this.btnAcheter.IdleFillColor = System.Drawing.Color.IndianRed;
            this.btnAcheter.IdleIconLeftImage = null;
            this.btnAcheter.IdleIconRightImage = null;
            this.btnAcheter.IndicateFocus = false;
            this.btnAcheter.Location = new System.Drawing.Point(915, 629);
            this.btnAcheter.Name = "btnAcheter";
            this.btnAcheter.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAcheter.OnDisabledState.BorderRadius = 1;
            this.btnAcheter.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAcheter.OnDisabledState.BorderThickness = 1;
            this.btnAcheter.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAcheter.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAcheter.OnDisabledState.IconLeftImage = null;
            this.btnAcheter.OnDisabledState.IconRightImage = null;
            this.btnAcheter.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAcheter.onHoverState.BorderRadius = 1;
            this.btnAcheter.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAcheter.onHoverState.BorderThickness = 1;
            this.btnAcheter.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAcheter.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAcheter.onHoverState.IconLeftImage = null;
            this.btnAcheter.onHoverState.IconRightImage = null;
            this.btnAcheter.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnAcheter.OnIdleState.BorderRadius = 1;
            this.btnAcheter.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAcheter.OnIdleState.BorderThickness = 1;
            this.btnAcheter.OnIdleState.FillColor = System.Drawing.Color.IndianRed;
            this.btnAcheter.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAcheter.OnIdleState.IconLeftImage = null;
            this.btnAcheter.OnIdleState.IconRightImage = null;
            this.btnAcheter.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAcheter.OnPressedState.BorderRadius = 1;
            this.btnAcheter.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAcheter.OnPressedState.BorderThickness = 1;
            this.btnAcheter.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAcheter.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAcheter.OnPressedState.IconLeftImage = null;
            this.btnAcheter.OnPressedState.IconRightImage = null;
            this.btnAcheter.Size = new System.Drawing.Size(165, 41);
            this.btnAcheter.TabIndex = 269;
            this.btnAcheter.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAcheter.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAcheter.TextMarginLeft = 0;
            this.btnAcheter.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAcheter.UseDefaultRadiusAndThickness = true;
            this.btnAcheter.Click += new System.EventHandler(this.btnAcheter_Click);
            // 
            // btntrouver
            // 
            this.btntrouver.AllowAnimations = true;
            this.btntrouver.AllowMouseEffects = true;
            this.btntrouver.AllowToggling = false;
            this.btntrouver.AnimationSpeed = 200;
            this.btntrouver.AutoGenerateColors = false;
            this.btntrouver.AutoRoundBorders = true;
            this.btntrouver.AutoSizeLeftIcon = true;
            this.btntrouver.AutoSizeRightIcon = true;
            this.btntrouver.BackColor = System.Drawing.Color.Transparent;
            this.btntrouver.BackColor1 = System.Drawing.Color.Maroon;
            this.btntrouver.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btntrouver.BackgroundImage")));
            this.btntrouver.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btntrouver.ButtonText = "affiche les informations";
            this.btntrouver.ButtonTextMarginLeft = 0;
            this.btntrouver.ColorContrastOnClick = 45;
            this.btntrouver.ColorContrastOnHover = 45;
            this.btntrouver.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btntrouver.CustomizableEdges = borderEdges2;
            this.btntrouver.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btntrouver.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btntrouver.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btntrouver.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btntrouver.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btntrouver.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btntrouver.ForeColor = System.Drawing.Color.White;
            this.btntrouver.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btntrouver.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btntrouver.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btntrouver.IconMarginLeft = 11;
            this.btntrouver.IconPadding = 10;
            this.btntrouver.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btntrouver.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btntrouver.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btntrouver.IconSize = 25;
            this.btntrouver.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btntrouver.IdleBorderRadius = 39;
            this.btntrouver.IdleBorderThickness = 1;
            this.btntrouver.IdleFillColor = System.Drawing.Color.Maroon;
            this.btntrouver.IdleIconLeftImage = null;
            this.btntrouver.IdleIconRightImage = null;
            this.btntrouver.IndicateFocus = false;
            this.btntrouver.Location = new System.Drawing.Point(60, 137);
            this.btntrouver.Name = "btntrouver";
            this.btntrouver.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btntrouver.OnDisabledState.BorderRadius = 1;
            this.btntrouver.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btntrouver.OnDisabledState.BorderThickness = 1;
            this.btntrouver.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btntrouver.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btntrouver.OnDisabledState.IconLeftImage = null;
            this.btntrouver.OnDisabledState.IconRightImage = null;
            this.btntrouver.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btntrouver.onHoverState.BorderRadius = 1;
            this.btntrouver.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btntrouver.onHoverState.BorderThickness = 1;
            this.btntrouver.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btntrouver.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btntrouver.onHoverState.IconLeftImage = null;
            this.btntrouver.onHoverState.IconRightImage = null;
            this.btntrouver.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btntrouver.OnIdleState.BorderRadius = 1;
            this.btntrouver.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btntrouver.OnIdleState.BorderThickness = 1;
            this.btntrouver.OnIdleState.FillColor = System.Drawing.Color.Maroon;
            this.btntrouver.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btntrouver.OnIdleState.IconLeftImage = null;
            this.btntrouver.OnIdleState.IconRightImage = null;
            this.btntrouver.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btntrouver.OnPressedState.BorderRadius = 1;
            this.btntrouver.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btntrouver.OnPressedState.BorderThickness = 1;
            this.btntrouver.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btntrouver.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btntrouver.OnPressedState.IconLeftImage = null;
            this.btntrouver.OnPressedState.IconRightImage = null;
            this.btntrouver.Size = new System.Drawing.Size(232, 41);
            this.btntrouver.TabIndex = 273;
            this.btntrouver.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btntrouver.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btntrouver.TextMarginLeft = 0;
            this.btntrouver.TextPadding = new System.Windows.Forms.Padding(0);
            this.btntrouver.UseDefaultRadiusAndThickness = true;
            this.btntrouver.Click += new System.EventHandler(this.btntrouver_Click);
            // 
            // bunifuTextBox3
            // 
            this.bunifuTextBox3.AcceptsReturn = false;
            this.bunifuTextBox3.AcceptsTab = false;
            this.bunifuTextBox3.AnimationSpeed = 200;
            this.bunifuTextBox3.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox3.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox3.AutoSize = true;
            this.bunifuTextBox3.BackColor = System.Drawing.Color.White;
            this.bunifuTextBox3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox3.BackgroundImage")));
            this.bunifuTextBox3.BorderColorActive = System.Drawing.Color.DarkMagenta;
            this.bunifuTextBox3.BorderColorDisabled = System.Drawing.Color.Azure;
            this.bunifuTextBox3.BorderColorHover = System.Drawing.Color.Magenta;
            this.bunifuTextBox3.BorderColorIdle = System.Drawing.Color.Maroon;
            this.bunifuTextBox3.BorderRadius = 1;
            this.bunifuTextBox3.BorderThickness = 4;
            this.bunifuTextBox3.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox3.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox3.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBox3.DefaultText = "";
            this.bunifuTextBox3.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox3.HideSelection = true;
            this.bunifuTextBox3.IconLeft = null;
            this.bunifuTextBox3.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox3.IconPadding = 10;
            this.bunifuTextBox3.IconRight = null;
            this.bunifuTextBox3.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox3.Lines = new string[0];
            this.bunifuTextBox3.Location = new System.Drawing.Point(561, 148);
            this.bunifuTextBox3.MaxLength = 32767;
            this.bunifuTextBox3.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox3.Modified = false;
            this.bunifuTextBox3.Multiline = false;
            this.bunifuTextBox3.Name = "bunifuTextBox3";
            stateProperties29.BorderColor = System.Drawing.Color.DarkMagenta;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox3.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.Azure;
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox3.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.Magenta;
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox3.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Maroon;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox3.OnIdleState = stateProperties32;
            this.bunifuTextBox3.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox3.PasswordChar = '\0';
            this.bunifuTextBox3.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox3.PlaceholderText = "Tapez ici ";
            this.bunifuTextBox3.ReadOnly = false;
            this.bunifuTextBox3.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox3.SelectedText = "";
            this.bunifuTextBox3.SelectionLength = 0;
            this.bunifuTextBox3.SelectionStart = 0;
            this.bunifuTextBox3.ShortcutsEnabled = true;
            this.bunifuTextBox3.Size = new System.Drawing.Size(272, 41);
            this.bunifuTextBox3.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBox3.TabIndex = 274;
            this.bunifuTextBox3.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox3.TextMarginBottom = 0;
            this.bunifuTextBox3.TextMarginLeft = -9;
            this.bunifuTextBox3.TextMarginTop = 0;
            this.bunifuTextBox3.TextPlaceholder = "Tapez ici ";
            this.bunifuTextBox3.UseSystemPasswordChar = false;
            this.bunifuTextBox3.WordWrap = true;
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.BackColor = System.Drawing.Color.Transparent;
            this.label9.Font = new System.Drawing.Font("Ink Free", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label9.Location = new System.Drawing.Point(556, 118);
            this.label9.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(142, 27);
            this.label9.TabIndex = 275;
            this.label9.Text = "Nom Complet";
            // 
            // UCgetionAchats
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ButtonHighlight;
            this.Controls.Add(this.label9);
            this.Controls.Add(this.bunifuTextBox3);
            this.Controls.Add(this.btntrouver);
            this.Controls.Add(this.btnAcheter);
            this.Controls.Add(this.GriAchat);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.TXTProduitNom);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.txtTotal);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.TXTquantite);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.TXTprix);
            this.Controls.Add(this.lblnumero);
            this.Controls.Add(this.DPdate);
            this.Controls.Add(this.lblNOms);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.TXTnumero);
            this.Controls.Add(this.TXTtele);
            this.Controls.Add(this.TXTnomcomplet);
            this.Controls.Add(this.label1);
            this.Name = "UCgetionAchats";
            this.Size = new System.Drawing.Size(1100, 755);
            this.Load += new System.EventHandler(this.UCgetionAchats_Load);
            ((System.ComponentModel.ISupportInitialize)(this.GriAchat)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label lblnumero;
        private Bunifu.UI.WinForms.BunifuDatePicker DPdate;
        private System.Windows.Forms.Label lblNOms;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox TXTnumero;
        private Bunifu.UI.WinForms.BunifuTextBox TXTtele;
        private Bunifu.UI.WinForms.BunifuTextBox TXTnomcomplet;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuDataGridView GriAchat;
        private System.Windows.Forms.Label label10;
        private Bunifu.UI.WinForms.BunifuTextBox TXTProduitNom;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuTextBox txtTotal;
        private System.Windows.Forms.Label label4;
        private Bunifu.UI.WinForms.BunifuTextBox TXTquantite;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuTextBox TXTprix;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAcheter;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btntrouver;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox3;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.DataGridViewTextBoxColumn NomProduit;
        private System.Windows.Forms.DataGridViewTextBoxColumn Prix;
        private System.Windows.Forms.DataGridViewTextBoxColumn Total;
    }
}
